import { Button } from 'antd';
import Head from 'next/head';
import PrimaryLayout from '../components/layouts/PrimaryLayout';
import styles from '../styles/Home.module.less';
import { NextPageWithLayout } from './page';

const Home: NextPageWithLayout = () => {
  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className={styles.container}>Index page</h1>
      <Button type="primary">Ant Button</Button>
    </div>
  );
};

export default Home;

Home.getLayout = (page) => {
  return <PrimaryLayout>{page}</PrimaryLayout>;
};
